/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CoordenadoresRouteImport } from './routes/coordenadores'
import { Route as MinhasInscricoesRouteImport } from './routes/minhas-inscricoes'
import { Route as MissasRouteImport } from './routes/missas'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoordenadoresRoute = CoordenadoresRouteImport.update({
  id: '/coordenadores',
  path: '/coordenadores',
  getParentRoute: () => rootRouteImport,
} as any)
const MinhasInscricoesRoute = MinhasInscricoesRouteImport.update({
  id: '/minhas-inscricoes',
  path: '/minhas-inscricoes',
  getParentRoute: () => rootRouteImport,
} as any)
const MissasRoute = MissasRouteImport.update({
  id: '/missas',
  path: '/missas',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/coordenadores': typeof CoordenadoresRoute
  '/minhas-inscricoes': typeof MinhasInscricoesRoute
  '/missas': typeof MissasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/coordenadores': typeof CoordenadoresRoute
  '/minhas-inscricoes': typeof MinhasInscricoesRoute
  '/missas': typeof MissasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/coordenadores': typeof CoordenadoresRoute
  '/minhas-inscricoes': typeof MinhasInscricoesRoute
  '/missas': typeof MissasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/coordenadores' | '/minhas-inscricoes' | '/missas'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/coordenadores' | '/minhas-inscricoes' | '/missas'
  id: '__root__' | '/' | '/coordenadores' | '/minhas-inscricoes' | '/missas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CoordenadoresRoute: typeof CoordenadoresRoute
  MinhasInscricoesRoute: typeof MinhasInscricoesRoute
  MissasRoute: typeof MissasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coordenadores': {
      id: '/coordenadores'
      path: '/coordenadores'
      fullPath: '/coordenadores'
      preLoaderRoute: typeof CoordenadoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/minhas-inscricoes': {
      id: '/minhas-inscricoes'
      path: '/minhas-inscricoes'
      fullPath: '/minhas-inscricoes'
      preLoaderRoute: typeof MinhasInscricoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/missas': {
      id: '/missas'
      path: '/missas'
      fullPath: '/missas'
      preLoaderRoute: typeof MissasRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CoordenadoresRoute: CoordenadoresRoute,
  MinhasInscricoesRoute: MinhasInscricoesRoute,
  MissasRoute: MissasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
